## Formación profesional

Ingeniero Mecánico Electricista, Facultad de Ingeniería Mecánica y
Eléctrica, Universidad de Colima, Coquimatlán, Colima, México, de 1996 a
2001. Fecha de obtención del título: Julio de 2001. Título de la tesis:
Cálculo del flujo para un extrusor de laboratorio para reología capilar.

Maestro en Ingeniería, Área Energía, Centro de Investigación en Energía,
Universidad Nacional Autónoma de México. Fecha de obtención del título:
21 de noviembre de 2003. Título de la tesis: Convección natural usando
el método de la ecuación de Boltzmann en redes.

Doctor en Ingeniería, Área Mecánica, Centro de Investigación en Energía,
Universidad Nacional Autónoma de México. Título de la tesis: Levitación
acústica usando el método de la ecuación de Boltzmann en redes.

Estancia posdoctoral en el departamento de Física de la Facultad de
Ciencias, UNAM. Tutor: Dr. Iván Santamaría Holek. Proyecto: Movimiento
no Browniano en flujos cortantes oscilatorios. Agosto 2007– Junio 2009.

Estancia posdoctoral en el programa Scientific Computing Advanced
Training, en el Centro Tecnológico de Transferencia de Calor,
Universidad Politécnica de Cataluña, España, Junio 2008 – Diciembre
2008. Proyecto: Desarrollo de un código híbrido para resolver problemas
con transferencia de calor en fluidos usando el método de la ecuación de
Boltzmann en redes y volumen finito.

Estancia posdoctoral en el proyecto FOMIX CONACyT – Estado de Morelos
"Estrategias de enfriamiento de bajo consumo energético para zonas del
estado de Morelos con clima cálido-subhúmedo" bajo la supervisión del
Dr. Jorge Rojas. Agosto 2009 – Febrero 2010.

Investigador en el Instituto de Energías Renovables en la línea de
investigación de análisis térmico de edificaciones. Febrero 2010 a la
fecha.


### Cursos de actualización

Conceptos básico para la igualdad de género. Coursera-UNAM. Diciembre 2022.

Igualdad de género y derechos humanos. Coursera-UNAM. Enero 2024.

Soy sólo yo mismx: un viaje por la neurodivergencia. IER-UNAM. Junio 2024



