## Distinciones y promociones

1.  Reconocimiento de alto rendimiento académico avalado por CENEVAL en
    la licenciatura Ingeniería Mecánica y Eléctrica.

2.  Mención honorífica en la Maestría en Ingeniería, Área Energía por la
    UNAM.

3.  Mención honorífica en el Doctorado en Ingeniería, Área Mecánica por
    la UNAM.

### CONACyT

1.  Miembro del Sistema Nacional de Investigadores, nivel 1.

### UNAM

1.  Investigador Asociado C de tiempo completo en el Instituto de
    Energías Renovables en la línea de investigación de análisis térmico
    de edificaciones. Febrero 2010 - Agosto 2018.

2.  Investigador Titular A de tiempo completo en el Instituto de
    Energías Renovables en la línea de investigación de análisis térmico
    de edificaciones. Agosto 2018 a la fecha.

3.  Investigador Titular A Definitivo de tiempo completo en el Instituto
    de Energías Renovables en la línea de investigación de análisis
    térmico de edificaciones. Noviembre 2018.

4.  PRIDE C, Febrero 2021.
