## Artículos

### Revistas indizadas por el *ISI Web of Knowledge*

1.  G. Barrios del Valle, R. Rechtman, J. Rojas, R. Tovar, The Lattice
    Boltzmann Equation for Natural Convection in a Partially Heated
    Cavity, Journal of Fluid Mechanics, **522** 91–100, 2005.

2.  G. Barrios, R. Rechtman, Dynamics of an acoustically levitated
    particle using the lattice Boltzmann method. Journal of Fluid
    Mechanics, **596** 191–299, 2008.

3.  I. Santamaría-Holek, G. Barrios, M. Rubi, Transition to
    irreversibility in sheared suspensions: An analysis based on a
    mesoscopic entropy production, Phys. Rev. E. (79), 3, 2009.

4.  I. Santamaría-Holek, G. Barrios, Statistical description of the
    shear-diffusion of a suspension of non-Brownian particles, Rev. Mex.
    Fís. **55**, (2), 2009.

5.  G. Barrios, G. Huelsz, R. Rechtman, J. Rojas, Wall/roof thermal
    performance differences between air-conditioned and non
    air-conditioned rooms. Energy and Buildings, **43**, 219–223, 2011.

6.  G. Barrios, G. Huelsz, J. Rojas, Thermal performance of envelope
    wall/roofs of intermittent air-conditioned rooms. Applied Thermal
    Engineering, **40**, 1–7, 2012.

7.  G. Barrios, G. Huelsz, J. Rojas, Envelope wall/roof thermal
    performance parameters for non air-conditioned buildings. Energy and
    Buildings, **50**, 120–127, 2012.

8.  J. Rojas, G. Barrios, G. Huelsz, R. Tovar y S. Jalife-Lozano,
    Thermal performance of two envelope constructive systems:
    measurements in non air-conditioned outdoor full-scale test-cells
    and simulations. Journal of Building Physics, **39** (5), 2016.

9.  G. Barrios, J.M. Casas, G. Huelsz, J. Rojas, Ener-Habitat: An online
    numerical tool to evaluate the thermal performance of homogeneous
    and non-homogeneous envelope walls/roofs. Solar Energy **131**,
    296–304,2016.

10. G. Huelsz, G. Barrios, J. Rojas, Equivalent-homogeneous-layers-set
    method for time-dependent heat transfer through hollow-block walls.
    Applied Thermal Engineering **102** (5), 1019–1023, 2016.

11. G. Barrios, J. Rojas, G. Huelsz, R. Tovar, S. Jalife, Implementation
    of the equivalent-homogeneous-layers-set method in whole-building
    simulations: Experimental validation Applied Thermal Engineering
    **125**, 35–40, 2017.

12. E. Moreles, G. Huelsz, G. Barrios, Hysteresis effects on the thermal
    performance of building envelope PCM-walls Building Simulation
    **11**, 3, 519–531, 2018.

13. G. Barrios, G. Huelsz, R. Recthman. Heat transfer and flow
    transitions of a thermal plume generated by a heating element on the
    enclosure bottom wall. European Journal of Mecanics-B/Fluids **77**,
    17–24, 2019.

14. G. Huelsz, G. Barrios, J. Rojas. Evaluation of heat transfer models
    for hollow blocks in whole-building energy simulations. Energy and
    Buildings **202**, 2019.

15. I Calixto-Aguirre, G Huelsz, G Barrios, MV Cruz-Salas. Validation of
    thermal simulations of a non-air-conditioned office building in
    different seasonal, occupancy and ventilation conditions. Journal of
    Building Engineering **44**, 2021.


17. G. Ramírez-Zúñiga, G. Barrios, G. Huelsz Lesbros, V. Sattele.
    Didactic device for teaching the importance of the time-dependent
    model for the heat transfer calculations in constructive systems of
    buildings. Journal of Building Physics, 2022.



18. J. Landa, G. Barrios, G. Huelsz, IoT smartwatch based on open technologies
    for the collection of thermal comfort data, HardwareX, 2025.





### Latindex

1. G. Huelsz Lesbros, J. Rojas, G. Álvarez-Almeida, G. Barrios.
    Importance of taking into account the thermal mass in simulations
    for a non-air-conditioned house. Ingeniería, Investigación y
    Tecnología, (XXIII) **3**, 2022.


2.  JM Ochoa, I. Marincic, G. Huelsz, G. Barrios,
    Transferencia dinámica de calor en muros de block hueco en una vivienda
    con ventilación natural. Vivienda y comunidades sustentables (7) 14, 2023.

3. G. Ramírez, G. Barrios, G. Huelsz, HD. Cortés, Diseño, construcción y
    caracterización de un monitor de CO2 para la calidad del aire de interiores
    y ventilación, compatible con tres sensores, con integración IoT, autoprueba
    y autodiagnóstico. Pistas Educativas 149, 2025.
    

4. G. Barrios. Enseñar a programar en la era de la IA generativa. Revista
    mexicana de Bachillerato a distancia, 34(17), 2025.

### UNAM

1. Grupo de trabajo de Inteligencia Artificial Generativa de la UNAM.
    Recomendaciones para el uso de la inteligencia artificial generativa en la
    docencia. Primera edición: octubre de 2023. 


2. Grupo académico  de Inteligencia Artificial Generativa en Educación UNAM 2025.
    Recomendaciones para el uso de la inteligencia artificial generativa en la
    docencia. Segunda edición: mayo de 2025. 



### Artículos de congresos indizados por el *ISI Web of Knowledge*

1.  I. Santamaria-Holek, G. Barrios, JM. Rubi, Transition to
    irreversibility in sheared suspensions, IV Mexican Meeting on
    Mathematical and Experimental Physics: Relativistic Fluids and
    Biological Physics, AIP Conference Proceedings, **1312**, 114–123,
    2010.

2.  JM. Ochoa, I. Marincic, MG. Alpuche, EA. Duarte, L. Gonzalez, G.
    Huelsz, G. Barrios, Cost benefit energy analysis of the building
    envelope systems with Ener-Habitat, 2013 ISES SOLAR WORLD CONGRESS,
    Energy Procedia **57**, 1792–1797, 2014, doi:
    10.1016/j.egypro.2014.10.042

3.  G. Huelsz, G. Barrios, J. Rojas, Differences on results from
    steady-state and time-dependent wall/roof heat transfer models in
    mexican climates, 2013 ISES SOLAR WORLD CONGRESS, Energy Procedia
    **57**, 1825–1833, 2014, doi: 10.1016/j.egypro.2014.10.046

4.  G. Barrios, G. Huelsz, J. Rojas, Ener-Habitat: A cloud computing
    numerical tool to evaluate the thermal performance of walls/roofs,
    2013 ISES SOLAR WORLD CONGRESS, Energy Procedia **57**, 2042–2051,
    2014, doi: 10.1016/j.egypro.2014.10.169
