## Comités de tesis

### Licenciatura

1.  Pablo Israel Bahena Castelar, Diseño de viviendas térmicamente
    confortables con uso de sistemas pasivos de climatización en la zona
    de Temixco: guía para constructores. Ingeniería en Tecnología
    Ambiental, Universidad Politécnica del Estado de Morelos. Examen de
    grado presentado en marzo del 2013.

### Maestría

1.  Ledín Rodríguez López, Maestría en Ingeniería, Campo de Conocimiento
    Energía, Universidad Nacional Autónoma de México, Examen de grado
    presentado en agosto del 2013.

2.  Jorge Belaunzarán Zamudio, Maestría en Ingeniería, Campo de
    Conocimiento Energía, Universidad Nacional Autónoma de México,
    Examen de grado presentado en enero del 2016.

3.  Efraín A. Puerto Castellanos, Maestría en Ingeniería, Campo de
    Conocimiento Energía, Universidad Nacional Autónoma de México,
    Examen de grado presentado en enero del 2018.

4.  Ana Gabriela Álvarez Almeida, Maestría en Ingeniería, Campo de
    Conocimiento Energía, Universidad Nacional Autónoma de México,
    Examen de grado presentado en noviembre del 2018.

5.  Gerardo Rangel Paredes, Maestría en Ingeniería, Campo de
    Conocimiento Energía, Universidad Nacional Autónoma de México,
    Examen de grado presentado en febrero del 2019.

6.  Sonny Francisco Díaz Calderón, Maestría en Ingeniería, Campo de
    Conocimiento Energía, Universidad Nacional Autónoma de México,
    Examen de grado presentado en enero del 2020.

7.  Verónica Ivette Calixto Aguirre, Maestría en Ingeniería, Campo de
    Conocimiento Energía, Universidad Nacional Autónoma de México,
    Examen de grado presentado en septiembre del 2021.

8.  Jeanette Alejandra García Morales, Maestría en Ingeniería, Campo de
    Conocimiento Energía, Universidad Nacional Autónoma de México,
    Examen de grado presentado en febrero del 2022.

9.  Humberto Ceballos Gallardo, Maestría en Arquitectura, Urbanismo y
    Diseño, Facultad de Ciencias de la Ingeniería y Tecnología,
    Universidad Autónoma de Baja California, 10 de junio 2022.

### Doctorado

1.  José Antonio Castillo Torres, Doctorado en Ingeniería, Campo de
    Conocimiento Energía, UNAM. Examen de grado presentado en febrero
    del 2016.

2.  Efraín Moreles Vázquez, Doctorado en Ingeniería, Campo de
    Conocimiento Energía, UNAM. Examen de grado presentado en enero del 2018.

3.  Miriam Veronica Cruz Salas, estudiante del Programa de Doctorado en
    Ingeniería, Campo de Conocimiento Energía, UNAM. Examen de grado
    presentado en julio del 2018.

4.  Polar Hernández Castillo, estudiante del Programa de Doctorado en
    Ingeniería, Campo de Conocimiento Energía, UNAM. Doctorado en
    proceso.

5.  Laura Sofía Hoyos Gómez, estudiante de la Facultad de Ingeniería y
    Arquitectura del Departamento de Eléctrica y Electrónica y
    Computación de la Universidad Nacional de Colombia, mayo 2021.
