## Consultorias

1.  Diseño térmico de la Casa-Lomas del proyecto de Habitaly, 2010.
    Participé en la estrategia de optimización de la captación de
    energía solar sobre la envolvente de la casa.

2.  Loft Boutique 2011 , Diseño bioclimático de una torre de
    departamentos ubicado en Lima, Perú. Arquitectum 2011. Participé en
    el diseño de las estrategias de ventilación cruzada y orientación.

3.  CASA-UNAM, Solar Decathlon Europe, 2013. Asesoré a los participantes
    del proyecto en los cálculos realizados con EnergyPlus y en el
    diseño de la envolvente.

4.  *Protecciones Solares en Fachadas del Edificio 12 del Instituto
    Nacional de Electricidad y Energías Limpias.* Instituto Nacional de
    Electricidad y Energías Limpias. Responsables del proyecto: Dra.
    Guadalupe Huelsz y Dr. Jorge Rojas. Mi participación consistió en
    proponer la metodología y dirigir las simulaciones para evaluar las
    propuestas de protecciones solares para el edificio. Agosto, 2016.

5.  *Asesoría a Estudio Daniela Barrera, proyecto 28_OFTL_OFICINAS
    TOLUCA UAEMex* Estudio Daniela Barrera, Octubre 2019. Responsables
    del proyecto: Dr. Jorge Rojas. Mi participación consistió en revisar
    el análisis de datos de viento, revisar las simulaciones y analizar
    los resultados de las propuestas hechas.

6. Asesoría-Diagnóstico y recomendaciones cualitativas del edificio de Ingenierias
    y construcción del Instituto Federal de Telecomunicaciones. G. Huelsz, J. Rojas,
    G. Barrios, JA Huelsz. Mi participación consistió en la instrumentación, adquisición
    y análisis de los datos y en las recomendaciones generales. 2024.

7. Reporte de mediciones "Fuerte de Bambú", Las Estacas, Morelos. G. Barrios, M. Cruz.
    Mi participación consistió en realizar las mediciones, interpretar los resultados
    y dirigir la realización del reporte. 2025.
