## Memorias en congresos nacionales

<div class="list">


G. Barrios, G. Huelsz, J. Rojas, Análisis de indicadores del desempeño
térmico de la envolvente de una edificación. XXXIV Semana Nacional de
Energía Solar, ANES Octubre-2010, Guanajuato, México.

G. Huelsz, G. Barrios, J. Rojas, Selección de los materiales de muros y
techos para mejorar el confort térmico en edificaciones no climatizadas,
Revista Estudios sobre Arquitectura y Urbanismo del Desierto, editada
por el Programa de Arquitectura de la Universidad de Sonora. Aceptado el
19 de Agosto de 2010.

M. Casas, G. Barrios, Revisión bibliográfica de lo publicado en el
congreso ANES sobre diseño bioclimático , XXXV Semana Nacional de
Energía Solar, Chihuahua, Chihuahua, Septiembre de 2011.

G. Barrios, G. Huelsz, J. Rojas, Evaluación de sistemas constructivos de
la envolvente usando sistemas de aire acondicionado intermitente, XXXV
Semana Nacional de Energía Solar, Chihuahua, Chihuahua, Septiembre de
2011.

G. Barrios, G. Huelsz, J. Rojas, Herramienta numérica para la evaluación
térmica de la envolvente de una edificación, XXXV Semana Nacional de
Energía Solar, Chihuahua, Chihuahua, Septiembre de 2011.

G. Huelsz, G. Barrios, J. Rojas, M. Salas, J.M. Ochoa, I. Barrera,
Ener-Habitat: herramienta numérica para la evaluación térmica de la
envolvente de una edificacióon, XXXVI Semana Nacional de Energía Solar,
ANES, 2012.

G. Barrios, G. Huelsz, J. Rojas, Parámetros para medir el desempe’no
térmico de muros/techos de la envolvente de una edificación que no usa
aire acondicionado, XXXVI Semana Nacional de Energía Solar, ANES, 2012.

A. Lira, J. Rojas, G. Huelsz, G. Barrios, F. Rojas, Protecciones solares
en fachadas del nuevo edificio de laboratorios del CIE: efectos en
radiación y en iluminación, XXXVI Semana Nacional de Energía Solar,
ANES, 2012.

Validación de Ener-Habitat para la evaluación de muros/techos no
homogéneos. G. Barrios, G. Huelsz, J. Rojas, XXXVIII Semana Nacional de
Energía Solar, XI Congreso Iberoamericano, Querétaro, Qro. del 8 al 10
de octubre del 2014.

Comparación del desempeño térmico de sistemas constructivos de techo y
muro usados en México. G. Huelsz, G. Barrios, J. Rojas, XXXVIII Semana
Nacional de Energía Solar, XI Congreso Iberoamericano, Querétaro, Qro.
del 8 al 10 de octubre del 2014.

Dispositivo para la enseñanza de la importancia del modelo dependiente
del tiempo en el cálculo de la transferencia de calor a través de la
envolvente. G. Huelsz, G. Barrios, G. Ramírez. XLIV Semana Nacional de
Energía Solar. 5 al 9 de octubre, 2020.

</div>
