## Divulgación

### Artículos

<div class="list">


J. Rojas, G. Huelsz, R. Tovar, G. Barrios, A. Lira-Oliver, A. Castillo
Energía y confort en edificaciones, Revista.unam.mx Revista Digital
Universitaria ISSN: 1607-6079 Octubre de 2010 Vol. 11, No. 10,  
http://www.revista.unam.mx/vol.11/num10/art92/

Ener-Habitat: Evaluación térmica de la envolvente arquitectónica en
México, G. Huelsz, G. Barrios, J. Rojas, Hypatia No. 45, Enero/Marzo
2013.

Ener-Habitat, una herramienta para mejorar el desempeño térmico de la
envolvente arquitectónica de edificaciones, G. Barrios, G. Huelsz y J.
Rojas, Revista Eficiencia Energética 5, 2015.

Edificio Sustentable: auxiliar en diseño bioclimático, G. Huelsz, J.
Rojas, G. Barrios, A. Castillo, MUNDO HVAC&R, Año XI, Número 126,
Octubre 2015.[url:
issuu.com/puntualmedia](issuu.com/puntualmedia/docs/revista_web_mh__octubre.compressed/1?e=18236302/30400988)

Entrevista para artículo de divulgación publicado. Herramienta para
evaluar el desempeño térmico, Mundo HVAC&R, Enero 2016.
[www.mundohvacr.com.mx](www.mundohvacr.com.mx/mundo/2016/01/herramienta-para-evaluar-el-desempeno-termico)

De Este a Oeste, de Norte a Sur, ¿en dónde aparece el Sol?, Periodico La
Unión de Morelos, 17 de diciembre de 2018.
[http://www.acmor.org.mx](http://www.acmor.org.mx/descargas/18_dic_17_sol.pdf)

Nicté Y. Luna Medina; Guillermo Barrios del Valle. “Monitores de CO₂ para la evaluación de espacios ventilados en el regreso a la presencialidad”, Academia de Ciencias de Morelos y  La Unión de Morelos, 20 de junio de 2022.

Diana Fernández, Itzel Aranguren-Navarro, Guillermo Barrios, Andrea Fernández. Programando la creatividad: el caso de Aaron, el robot pintor. Komputer Sapiens, Año XVII, No 3, Septiembre--Diciembre 2025.
</div>

### Café Científico

El "Café Científico" es un espacio informal, pero no por eso menos
exacto, donde buscamos compartir y debatir sobre temas de ciencia y
tecnología. Las charlas se llevan a cabo en un café ubicado en el centro
de Cuernavaca. La dinámica es sencilla, siempre invitamos a un experto
de un tema determinado, se hace un planteamiento del mismo y después
comenzamos a preguntar y a interactuar con el invitado especial. Todo
esto mientras bebes un café o consumes algo más. La entrada es libre y
puede asistir cualquiera que esté interesado en el tema.

<div class="list">



Dr. Raúl Rechtman Schrenzel ¿Qué caos nos importa?. 5/marzo/2015

Dr. Jesús Carlos Ruiz Suárez. Neurociencia: tequila y café.
26/marzo/2015

Dr. Mariano López de Haro. De canicas, besos, granos y otras cosas menos
mundanas. 30/abril/2015

Dra. Karla Cedano La sociofísica aplicada como herramienta para la toma
de decisiones. 4/junio/2015

Dr. Mario César Suárez Arriaga Cinco mil millones de años de historia de
la geotermia . Septiembre/2015.

Dr. Antonio del Río Portilla Termodinámica y sustentabilidad
29/octubre/2015.

Dr. Luca Ferrari. El futuro de la energía ¿es posible sustituir
petróleo, gas y carbón?. 26/noviembre/2015.

Dra. Guadalupe Huelsz Lesbros ¿Sirve la certificación de edificios en
energía y medio ambiente LEED?. 12/febrero/2016.

Dr. Luis Mochán. Física, matemáticas y sociedad: algunos encuentros.
14/abril/2016.

Dr. Jorge Islas Samperio. Mitigando las emisiones de gases de Efecto
Invernadero en México. 28/abril/2016.

Dr. Agustín López Munguia. Ciencia, tecnología, producción agrícola y
alimentación. 5/mayo/2016.

Dr. Sergio Cuevas Garcia. Michael Faraday y la confrontación de la
Naturaleza. 11/agosto/2016.

Dr. Jorge Wong. Leyes de Newton en la vida cotidiana. 8/septiembre/2016.

Dr. Alejandro Alagón Cano. Venenos y antivenenos. 13/octubre/2016.

Dr. Miguel Robles Pérez. Tres escalones para intentar entender el Nobel
de Física: entalpía, entropía y topología. 17/noviembre/2016.

Dra Ruth Davila. ¿La era Trump? Conversatorio sobre el ascenso a la
presidencia de los Estados Unidos de Donald Trump. 16/febrero/2017.

Fis. Juan Tonda Mazón . ¿Y tú qué ves? Ilusiones ópticas. 23/marzo/2017.

Dra. Antígona Segura. Vida extraterrestre, la visión de la ciencia.
27/abril/2017.

Dr. Enrique Reynaud. De moscas y cerebros. 25/mayo/2017.

Dr. Roberto Sussman. Cosmología, el estudio del universo en que vivimos.
7/septiembre/2017.

Dr. Franco Bagnoli. ¿Por qué el sexo es divertido?. 7/diciembre/2017.

Dr. Jesús Martínez. Vacunas: De lo molecular a lo social.
22/febrero/2018.

Dr. David Romero . El ajolote: un paseo por la cultura, la biología y la
genómica de un anfibio fascinante. 4/abril/2018.

Dr. Juan Carlos Hidalgo. ¿Que tan negro es un agujero negro? y otras
contribuciones científicas de Stephen Hawking. 17/mayo/2018.

Dra. Gloria Koenigsberger. Telescopios espaciales . 30/agosto/2018.

Arqueóloga Georgia Yris Bravo. Hallazgos arqueológicos recientes en
Teopanzolco . 20/septiembre/2018.

Bio. Agustín Ávila . Los homos perdidos, sexo y extinción en la
evolución humana. 18/octubre/2018.

Dr. Edmundo Calva. La ciencia y los valores humanos . 29/noviembre/2018.

Dra. Susana López Charretón. Mitos y realidades de las vacunas.
7/marzo/2019.

Dr. Aubin Arroyo. Nudos Salvajes . abril/2019.

Dr. Sebastien Fromenteau. Somos hijos de las fluctuaciones cuánticas
primordiales . 30/mayo/2019.

Bio. Agustín Ávila . La ecología del miedo. 29/agosto/2019.

Dr. Diego Cortez Quezada. Genómica de la sexualidad en vertebrados.
19/septiembre/2019.

Dr. Juan Carlos Degollado Daza. Agujeros negros, objetos extremos en el
universo. 17/octubre/2019.

Dra. Ruth A. Dávila Figueroa. ¡Extra! ¡Extra! Medios de comunicación,
periodismo y Fake News. 31/octubre/2019.

Dra. Ayari Fuentes Hernández. Evolución de resistencia a antibióticos.
28/noviembre/2019.

Dra. Yilen Gómez Maqueo Chew. Buscando exoplanetas desde México.
5/marzo/2020.

Dra. Karla Cedano. Economía y pobreza, enderezando el binomio.
26/marzo/2020 .

Dra. Susana López Charretón. Un nuevo virus emergente, el Coronavirus
SARS-Cov2: Situación actual en Mexico y en el mundo. 2/abril/2020

Dra. Ruth A. Dávila Figueroa. Fake news y periodismo en pandemia.
16/abril/2020.

Dra. Mariana Vargas Magaña, Dra. Rosa Maria Vargas Magaña, Dr. Sebastien
Fromenteau. Impacto de las Medidas de Control en la evolución del brote
COVID-19. 23/abril/2020.

Dr. Antonio del Rio Portilla. Energías Renovables en el México actual.
16/marzo/2021.

Dra. Úrsula Oswald. Cambio climático, agua, energía y sustentabilidad
desde las ciencias sociales. 18/mayo/2021.

Dr. Victor Ulises. Levitación acústica, cómo funciona y para que sirve ?
22/junio/2021.

Dra. Marina Rincón. Nanomateriales y energía. 28/septiembre/2021.

Dr. Steven Brunton. Brewing a coffee with a shot of math.
11/noviembre/2021.

M. Aleida Rueda. El periodismo de ciencia en la COP26. 22/febrero/2022.

Dra. Yilen Gómez. ¿Cómo se observa el Universo?. 19/mayo/2022.

Dr. Gerardo Herrera Corral. El bosón W y la supersimetría.
30/junio/2022.

</div>

### Tesis en corto

Tesis en Corto son videos con una duración entre 3 y 5 minutos donde un
estudiante describe lo que hizo durante su tesis de grado. Los videos se
suben a YouTube. Este proyecto se realiza en conjunto con la Maestra
Nicté Luna, académica del IER-UNAM. Este proyecto maduró y en el 2019,
la M. Nicté realizó la Primera Jornada de Tesis en Corto, con la
participación de 11 estudiantes. Yo estuve involucrado en el concepto y
revisiones de guiones hasta antes de la Primera Jornada. Se enlistan los
videos en que participé.

<div class="list">

.

Receptor Lineal Fresnel para Concentración Térmica y Fotovoltaica. Juan
Carlos Castro Domínguez. Subida el 13 de junio de 2016, 1432
reproducciones.

Métodos no convencionales en geoquímica de fluidos y de rocas. Erika
Almirudis Echeverría. Subida el 24 de enero de 2017, 534 reproducciones.

Validación de un simulador de intercambiador de calor de aire y tierra.
Irene Yasmín Díaz Vazquez. Subida el 24 de enero del 2017, 917
reproducciones.

Estudio de microalga con potencial bioenergético y de biorremediación
ambiental, Emilio Arena Guerrero. Subida el 25 de julio del 2017, 1083
reproducciones.

Diseño y aplicaciones de estructuras fotónicas de silicio poroso. Dense
Estrada Wiese. Subida el 10 de enero del 2018, 722 reproducciones.

Celdas solares de calcogenenuros de antimonio. Fabiola de Bray Sánchez.
Subida el 11 de diciembre de 2018, 389 reproducciones.

Celda de electrólisis microbiana para producir hidrógeno. Mónica Mejía.
Subida el 27 de marzo de 2019, 791 reproducciones.

</div>
