## Apoyo institucional

1.  Miembro de la comisión de cómputo desde marzo del 2012 a octubre 2013.

2.  Miembro de la comisión de ecología y entorno físico de octubre del
    2013 al 2018.

3.  Presidente de la comisión de vigilancia para la elección del
    Consejero Representante del Personal Académico del IER ante el
    CAACFMI, 14 de abril del 2016.

4.  Miembro del Consejo Interno desde febrero a diciembre del 2016 a
    como representante del Departamento de Termociencias.

5.  Miembro de la comisión de creación de examen de admisión de la
    LIER-2018, revisor de reactivos de matemáticas.

6.  Miembro de la comisión de creación de examen de admisión de la
    LIER-2019, revisor de reactivos de matemáticas.

7.  Jefe de la Unidad de computo y tecnologías de la información y
    comunicación desde marzo del 2019 a diciembre del 2020.

8.  Miembro de la comisión de creación de examen de admisión de la
    LIER-2020, revisor de reactivos de matemáticas.

9.  Desarrollo de un pizarrón de luz para la grabación de clases
    virtuales, noviembre 2020.

10. Suplente de contacto entre el IER-UNAM y el Programa Universitario
    de Investigación en Salud sobre la pandemia COVID-19.

11. Apoyo al Posgrado en Ingeniería, área Energía, en el examen de
    admisión Maestría-Doctorado semestre 2021-1.

12. Apoyo al Posgrado en Ingeniería, área Energía, en el examen de
    admisión de Doctorado semestre 2021-2.

13. Miembro de la comisión de creación de examen de admisión de la
    LIER-2021, revisor de reactivos de matemáticas.
    
14. Presidente del Comité Académica de Apoyo de Docencia y Divulgación,
enero 2021 a diciembre 2023. IER-UNAM.

15. Evaluador del Premio AFIRME-FUNAM 2021, 2da edición. 2021.

15. Integrante del Comité de Educación Continua del IER-UNAM. 2021--2023.

15. Organizador de la 22 escuela de investigación en energía, IER-UNAM.
Enero 2022.

15. Organizador de las Jornadas de Proyectos PAPIME 2022. IER-UNAM. 2022.

14. Miembro de la comisión de creación de examen de admisión de la
    LIER-2022, revisor de reactivos de matemáticas.

15. Miembro de la comisión de creación de examen de admisión de la
    LIER-2023, revisor de reactivos de matemáticas.

16. Evaluador del Premio AFIRME-FUNAM 2023, 4ta edición. 2024.

17. Dictaminador de las presentaciones relámpago. 2da Jornada de IA generativa en educación UNAM 2024.

18. Integrante del Subcomité de Servicio Social de la LIER-UNAM.
Febrero 2025 a la fecha.

19. Integrante del antes  Comité de Apoyo Académico de Divulgación y Docencia ahora Departamento 
de Innovación Estratégica del IER-UNAM del 1 de enero de 2025 a la fecha.
