## Estancias

VIII Verano de la investigación científica 1998. Investigador receptor:
Dr. José Luis Fernández Zayas, Instituto de Ingeniería, UNAM.

IX Verano de la investigación científica 1999. Investigador receptor:
Dr. Manuel Martínez Fernández , Centro de Investigación en Energía,
UNAM.

Movilidad Estudiantil Universidad de Colima-Universidad de Guanajuato.
Semestre 9 y 10 de la carrera en Ingeniería Mecánica Eléctrica.

Estancia, Dipartimento di Matematica Applicata, Università di Firenze,
Florencia, Italia, agosto–octubre de 2004. Anfitrión: Franco Bagnoli.

Centro Tecnológico de Transferencia de Calor, Universidad Politécnica de
Catalunya, becado por el programa Scientific Computing Advanced
Training, Julio – Diciembre de 2008.

Lawrence Berkeley National Laboratory. Proyecto: Edificios demostrativos
de diseño bioclimático en clima cálido subhúmedo en el Instituto de
Energías Renovables UNAM 4 al 8 febrero, 2019.

Lawrence Berkeley National Laboratory. Proyecto: Edificios demostrativos
de diseño bioclimático en clima cálido subhúmedo en el Instituto de
Energías Renovables UNAM 11 al 19 julio, 2019.
