## Trabajos presentados en congresos y reuniones

<div class="list">



F.Z. Sierra, E. Ramos, <u>G.Barrios</u>, M. Vargas Design and test of an
apparatus for natural convective cylindrical flows in static and
rotating systems. XVII Congreso Nacional de Instrumentación.

M. Cedillo, <u>G.Barrios</u>, G. Hernández. Solución Numérica de un
flujo laminar en una pared verticalmente calentada. VIII Congreso de la
División de Dinámica de Fluidos de la Sociedad Mexicana de Física,
Octubre 2002, Guanajuato, México.

<u>G.Barrios</u>, R. Rechtman. Estudio numérico de la convección natural
usando el método de la ecuación de Boltzmann en redes. IX Congreso de la
División de Dinámica de Fluidos, Octubre 2003, Distrito Federal, México.

<u>G.Barrios</u>, R. Rechtman. Convección natural en una cavidad
parcialmente calentada usando el método de la ecuación de Boltzmann en
redes. X Congreso de la División de Dinámica de Fluidos, Octubre 2004,
Sonora, México.

<u>G.Barrios</u>, R. Rechtman. Lattice Boltzmann equation for natural
convection with a partially heated wall. International Conference for
Mesoscopic Methods in Engineering and Science, Junio 2004, Braunschweig,
Alemania.

<u>G. Barrios</u>, <u>Raúl Rechtman</u>, Lattice Boltzmann equation for
natural convection inside a partially heated cavity, "Statistical
Mechanics, Chaos and Condensed Matter", Roma, Italia, 22 al 24 de
septiembre del 2004.

<u>G.Barrios</u>, G. Huelsz, R. Rechtman. Levitación acústica usando el
método de la ecuación de Boltzmann en redes. XI Congreso de la División
de Fluidos y Plasmas de la Sociedad Mexicana de Física, Septiembre 2005,
Jalisco, México.

<u>G.Barrios</u>, R. Rechtman. Interacción de plumas térmicas usando el
método de la ecuación de Boltzmann en redes. XI Congreso de la División
de Fluidos y Plasmas de la Sociedad Mexicana de Física, Septiembre 2005,
Jalisco, México.

G. Barrios, G. Huelsz, R. Rechtman. Oscilación de una pluma térmica en
una cavidad angosta usando la ecuación de Boltzmann en redes, XIII
Congreso de Dinámica de Fluidos y Plasmas de la Sociedad Mexicana de
Física, Boca del Rio, Ver., 1 de noviembre de 2007.

G. Barrios, G. Huelsz, R. Rechtman. Rompimiento de simetrías de una
pluma bidimensional en aire, XV Congreso de Dinámica de Fluidos y
Plasmas de la Sociedad Mexicana de Física, Acapulco, Gro., 29 de octubre
del 2009.

</div>
