## Citas

De acuerdo al *Web of Science* mi índice *h* es 8 y cuento con un total
de 229 citas. Mi artículo con más citas es:

- G. Barrios, R. Rechtman, J. Rojas, R. Tovar. The lattice Boltmann
  equation for natural convection in a two dimensional cavity with a
  partially heated wall, *Journal of Fluid Mechanics*, **522**, 91–100,
  2005,

cuenta con 66 citas, y los tres siguientes artículos más citados que
tengo son:

- G. Barrios, G. Huelsz, R. Rechtman, J. Rojas, Wall/roof thermal
  performance differences between air-conditioned and non
  air-conditioned rooms. *Energy and Buildings*, **43**, 219–223, 2011.

- G. Barrios, G. Huelsz, J. Rojas, Thermal performance of envelope
  wall/roofs of intermittent air-conditioned rooms. Applied Thermal
  Engineering, **40**, 1–7, 2012,

- G. Barrios, G. Huelsz, J. Rojas, Envelope wall/roof thermal
  performance parameters for non air-conditioned buildings. *Energy and
  Buildings*, **50**, 120–127, 2012.

y cuentan con 33, 30 y 30 citas, respectivamente.
