## Estudiantes

### Estancias profesionales

1.  Raúl Alejandro Camen Tepepa, Sensores embebidos en muros para flujo
    de calor, Ingeniería Electromecánica, Instituto Tecnológico de
    Zacatepec, Residencia profesional, junio 2021.

### Técnico Superior Universitario

1.  Juan Antonio Abarca Santa Olalla, Diseño de un prototipo de medición
    y adquisición basado en arduino, Técnico Superior Universitario en
    Mecatrónica, área Automatización, Universidad Tecnológica Emiliano
    Zapata del Estado de Morelos. Graduado en septiembre de 2016.

2.  Arturo Irineo Francisco, Lectura y adquisición de datos con software
    libre, Técnico Superior Universitario en Mecatrónica, área
    Automatización, Universidad Tecnológica Emiliano Zapata del Estado
    de Morelos. Graduado en septiembre de 2016.

3.  Miguel Angel Huertero Diego, Caracterización del sensor de viento
    Wind Sensor Rev. P., Técnico Superior Universitario en Mecatrónica,
    área Automatización, Universidad Tecnológica Emiliano Zapata del
    Estado de Morelos. Graduado en enero de 2017.

4.  Luis Fernando De Olarte Delgado, Diseño y construcción de
    instrumentos de medición del consumo de potencia eléctrica y agua en
    edificaciones, Técnico Superior Universitario en Ingeniería, área
    Mecánica industrial, Universidad Tecnológica Emiliano Zapata del
    Estado de Morelos. Graduado en mayo de 2019.

### Licenciatura

1.  Ingeniero en Mantenimiento Industrial Jorge Miguel Casas Arredondo,
    Universidad Tecnológica Emiliano Zapata, 2010. Estado del Arte de
    Energía en Edificaciones en México.

2.  Ingeniera en Tecnología Ambiental Ariadna Ocampo Astudillo,
    Universidad Politécnica del Estado de Morelos. Estudio numérico de
    la transferencia de calor en edificaciones para potencializar el
    ahorro energético en México. Abril 2015.

3.  Ingeniero en Mecatrónica Juan Antonio Abarca Santa Olalla,
    Universidad Tecnológica Emiliano Zapata. Diseño del control y
    visualización de datos para dispositivo didáctico para la enseñanza
    de la transferencia de calor en sistemas constructivos. Mayo 2018.

4.  Ingeniero en Mecatrónica José Luis Figueroa Millan, Universidad
    Tecnológica Emiliano Zapata. Fabricación y puesta a punto de
    circuitos electrónicos para aplicación en dispositivo didáctivo para
    la enseñanza de la transferencia de calor. Mayo 2018.

5.  Ingeniero en Tecnología Ambiental José María Aguilar Mier,
    Universidad Politécnica del Estado de Morelos. Validación de la
    simplificación del método EHLS para la transferencia de calor a
    través de la envolvente de una edificación. Julio 2018.

6.  Ingeniera en Energías Renovables Veronica Ivette Calixto Aguirre,
    Instituto de Energías Renovables,Universidad Nacional Autónoma de
    México. Methodology for the validation of thermal simulations of a
    real building. Marzo 2019.

7.  Ingeniero en Mecatrónica Victor Zamora Martínez, Universidad
    Tecnológica Emiliano Zapata. Unidad meteorológica para sensar
    variables de iluminación, sonido, temperatura y humedad ambiental en
    edificio sustentable. Mayo 2019.

8.  Ingeniera en Energías Renovables Paloma Xchel Vázquez Dávila,
    Instituto de Energías Renovables,Universidad Nacional Autónoma de
    México. Methodology to simulate a complex building using EnergyPlus:
    detailed case study for building 3.1. Junio 2019.

9.  Ingeniera en Energías Renovables Lucero Clarisa Betancourt García,
    Instituto de Energías Renovables, Universidad Nacional Autónoma de
    México. Simulación con Radiance de estrategias de iluminación
    natural para un espacio del IER. Enero 2020.

10. Ingeniero en Energías Renovables Eros Vladimir Rosete Sánchez,
    Instituto de Energías Renovables, Universidad Nacional Autónoma de
    México. Simulación y dimensionamiento de un sistema de enfriamiento
    radiativo para un espacio en un clima cálido sub-húmedo. Marzo 2021.

11. Ingeniera en Energías Renovables Mariana López Magaña , Instituto de
    Energías Renovables, Universidad Nacional Autónoma de México. High
    Dynamic Range photography for daylighting measurements with open
    technologies. Octubre 2021.

### Maestría

1.  Maestro en Ingeniería Jorge Miguel Casas Arredondo, alumno del plan
    de estudios del Programa de Maestría en Ingeniería, Campo de
    Conocimiento Energía, UNAM. Simulación térmica de edificaciones con
    EnergyPlus y Ener-Habitat: análisis de la interacción entre los
    componentes de la envolvente. Examen de grado presentado en agosto
    del 2014

2.  Maestra en Ingeniería Lucero Ángeles de la Cruz, alumna del plan de
    estudios del Programa de Maestría en Ingeniería, Campo de
    Conocimiento Energía, UNAM. Estudio de la transferencia de calor
    dependiente del tiempo en muros de bloques huecos de concreto.
    Examen de grado presentado en mayo del 2016.

3.  Arq. Luz Elena Moreyra González, Evaluación numérica de los efectos
    termoenergéticos de sistemas de acristalamiento en 2 climas de
    México, Maestría en Diseño, Línea Arquitectura Bioclimática,
    UAM-Azcapotzalco. Co-dirección con el Dr. Pablo Elías. Fecha de
    examen 9 de septiembre de 2016.

4.  Arq. Verushka Gómez Dickinson, Simulación de la iluminación natural
    y el desempeño térmico de un espacio con un tubo solar, Programa de
    Maestría en Ingeniería, Campo de Conocimiento Energía, Diseño
    Bioclimático, UNAM. Fecha de examen 3 de marzo de 2017.

5.  Ing. José Ignacio Maciel Hernández, Evaluation of the NZEB
    definitions in a new building at IER-UNAM, Programa de Maestría en
    Ingeniería, Campo de Conocimiento Energía, Diseño Bioclimático,
    UNAM. Fecha de examen 27 de junio de 2024.
