## Seminarios

<div class="list">



El método de la ecuación de Boltzmann en redes: Convección natural y
levitación acústica. Centro de Investigación y Estudio de Posgrado,
Facultad de Ingeniería, Universidad Autónoma de San Luis Potosí, 27 de
marzo de 2009.

El método de la ecuación de Boltzmann en redes: Convección natural y
levitación acústica. Facultad de Ciencias, Universidad Autónoma del
Estado de Morelos, 30 de octubre de 2009.

Interacciones hidrodinámicas en la transición a la irreversibilidad en
un flujo cortante oscilatorio Posgrado en Ingeniería Química,
Universidad de Guanajuato, 6 de noviembre de 2009.

Seminario de la Facultad de Ciencias, Uso de MPI en el método de la
ecuación de Boltzmann en redes, Facultad de Ciencias, UAEM, Cuernavaca,
Morelos, UAEM, 11 de abril de 2011.

Seminarios del CIByC, Energía en edificaciones: hacia una casa cero
energía, Centro de Investigación en Biodiversidad y Conservación, UAEM,
Cuernavaca, Morelos, 1 de julio de 2011.

Seminario del programa de posgrado en ingeniería, Hacia edificaciones
energía cero en México, Departamento de Ingeniería Química, Universidad
de Guanajuato, Guanajuato, 12 de agosto de 2011.

Seminarios del posgrado, Métodos numéricos para transferencia de calor y
masa, Centro de Investigación en Energía, UNAM, Temixco, Morelos, 10 de
octubre de 2011.

Seminario del departamento de Termociencias, Ener-Habitat, Centro de
Investigación en Energía, UNAM, Temixco, Morelos, 30 de noviembre de
2011.

Seminario del Posgrado, Departamento de Ingeniería Química.
Ener-Habitat: El método numérico detrás de la herramienta para evaluar
el desempe’no térmico de un muro/techo de una edificación. Universidad
de Guanajuato, 12 de abril de 2013.

Seminario de Eficiencia Energética en Edificaciones, Departamento de
Arquitectura y Dise’no, Ener-Habitat: Evaluación térmica de la
envolvente de edificaciones habitacionales. Universidad de Sonora, 31 de
febrero de 2013.

Congreso EDUCAREnovables. Energías Renovables: Hacia un futuro
sustentable. Universidad Autónoma de Durango, Campus Cuernavaca,
Morelos, 26 de septiembre de 2013.

Feria de Servicios Tecnológicos e Innovaciones en materia de TIC,
Presentación de Ener-Habitat. Centro Cultural Tlatelolco, Coordinación
de Innovación y Desarrollo, UNAM, 27 de septiembre de 2013.

Seminario y Taller, Panorama y perspectivas de la eficiencia energética
en edificaciones, Arquitectura Bioclimática. Importancia de la
transferencia de calor en edificaciones y como medirla. Universidad
Autónoma Metropolitana, 15 de noviembre de 2013.

Ener-Habitat: El método numérico detrás de la herramienta. Seminario del
Posgrado en Ingeniería, 25 de noviembre de 2013.

Interacción en la transferencia de calor en edificaciones, Seminario del
Posgrado en Ingeniería Química de la División de Ciencias Naturales y
Exactas, Guanajuato, Guanajuato, 3 de octubre de 2014.

Cómo medir el desempeño térmico de las edificaciones.XVIII Seminario
Peninsular Uso Eficiente de la Energía Eléctrica, Mérida, Yucatan, 6 y 7
de noviembre de 2014.

Edificaciones sustentables: El reto y como abordarlo, 24 Ideas que
Laten, Guanajuato, Gto, 21 y 22 de agosto del 2015.

Simulaciones numéricas para evaluar el desempeño de las edificaciones,
Fiesta de las ciencias y humanidades, 16 de octubre del 2015, DGDC–UNAM.

El reto de las edificaciones sustentables, Primer Foro de Innovación
Sustentable, 11 de noviembre del 2015, Universidad Americana de Morelos.

Simulaciones para evaluar el desempeño térmico e iluminación natural en
edificaciones, Concurso-Taller Centro Comunitario Bioclimático
Sustentable, 5 y 6 de abril del 2016, Facultad de Arquitectura–IER-UNAM.

Método de capas homogéneas equivalentes para transferencia de calor
dependiente del tiempo en muros con cavidades de aire, Seminario de los
Miércoles, 31 de mayo del 2017, Instituto de Energías Renovables, UNAM.

Método de capas homogéneas equivalentes para transferencia de calor
dependiente del tiempo en muros con cavidades de aire. Seminario
conjunto Ciencia de Materiales para el Desarrollo Sustentable. Instituto
de Investigaciones en Materiales y de la Escuela Nacional de Estudios
Superiores, UNAM. Morelia, 27 de octubre de 2017.

Confort higrotérmico y energía: Grupo Energía en Edificaciones, 3er
encuentro y 1er congreso internacional "Sustentabilidad energética,
medioambiente y sociedad". Red SUMAS, 11 al 15 de septiembre 2017,
Universidad Autónoma de Morelos.

Confort térmico y ahorro de energía en tu casa, Feria de las Ciencias y
las Humanidades 2017. Dirección General de Divulgación de la Ciencia,
UNAM.

Modelo simplificado para la transferencia de calor un bloques huecos de
concreto, Seminario de los Miércoles, 18 de abril del 2018, Instituto de
Energías Renovables, UNAM.

Análisis de datos para estudiar el comportamiento térmico de
edificaciones, Seminario del Posgrado de Ingeniería, Instituto de
Energías Renovables, UNAM. Temixco, Morelos a 12 de noviembre de 2018.

Webinar: Cuánta energía uso al ejercitarme. Serie Webinars Energía en la
vida cotidiana. Impartido con el Dr. Antonio del Rio en YouTube. 11 de
junio del 2020.

Prototipado rápido y ciencia libre: Monitor CO2, Seminarios Virtuales
del Instituto de Energías Renovables, UNAM. 1 de octubre de 2022. Zoom.

Webinar: Diseño bioclimático para el confort térmico y ahorro de
energía. Serie Webinars Energía en la vida cotidiana. Impartido con la
Dra. Guadalupe Huelsz. 10 de diciembre del 2020.

Dispositivos libres para generar mapas de iluminancia, Jornadas Peruanas
de Energía Solar - JOPES 2022. 13 de mayo de 2022, plataforma ZOOM.

Cambio de horario y energía en edificaciones, Secretaría de Medio
Ambiente y Recursos Naturales del Estado de Hidalgo, Zoom, 28 de marzo
2022.

</div>
